
services:
  backend:
    container_name: shf-backend
    build: .
    environment:
      - LD_LIBRARY_PATH=/usr/local/lib/
    depends_on:
    - db
    networks:
      - shf-network
    ports:
      - "8080:8080"
    restart: unless-stopped

  db:
    container_name: shf-database
    image: mongodb/mongodb-community-server:7.0.4-ubuntu2204
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=admin
    #   - MONGO_INITDB_ROOT_PASSWORD=admin123
    networks:
      - shf-network
    volumes:
      - database:/data/db
    restart: unless-stopped
    ports:
      - "27017:27017"

networks:
  shf-network:

volumes:
  database: